import type {
  AuditLog,
  Booking,
  MaintenanceIssue,
  PromoCode,
  Review,
  Room,
  RoomImage,
  StaffMember,
} from "@/lib/types"

function isoDateOffset(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString().slice(0, 10)
}

function isoDateTimeOffset(days: number, hours: number, minutes: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  date.setHours(hours, minutes, 0, 0)
  return date.toISOString()
}

// Each room's own two photos, in room order — reused across categories below so every
// room ends up with a small categorized gallery without needing brand-new image URLs.
const roomPhotoPairs: [string, string][] = [
  [
    "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1611048268330-53de574cae3b?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1595576508898-0ad5c879a061?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1631049035182-249067d7618e?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1591088398332-8a7791972843?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1618219944342-824e40a13285?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1592229505726-ca121723b8ef?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=1200&q=80",
  ],
  [
    "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1615873968403-89e068629265?auto=format&fit=crop&w=1200&q=80",
  ],
]

function roomImages(index: number): RoomImage[] {
  const [bedroom, view] = roomPhotoPairs[index]
  const [, bathroom] = roomPhotoPairs[(index + 3) % roomPhotoPairs.length]
  const [lounge] = roomPhotoPairs[(index + 6) % roomPhotoPairs.length]
  return [
    { url: bedroom, category: "Bedroom" },
    { url: bathroom, category: "Bathroom" },
    { url: lounge, category: "Lounge" },
    { url: view, category: "View" },
  ]
}

export const rooms: Room[] = [
  {
    id: "room-1",
    name: "Harbour Standard",
    type: "standard",
    description:
      "A bright, comfortable room with a queen bed and city views — ideal for short stays and solo travellers.",
    price: 480,
    images: roomImages(0),
    amenities: ["Free Wi-Fi", "Air conditioning", "Flat-screen TV", "En-suite bathroom"],
    capacity: 2,
    status: "available",
    rating: 4.72,
  },
  {
    id: "room-2",
    name: "Garden Deluxe",
    type: "deluxe",
    description:
      "A spacious deluxe room overlooking the courtyard garden, with a king bed and a private sitting area.",
    price: 780,
    images: roomImages(1),
    amenities: ["Free Wi-Fi", "Air conditioning", "Mini bar", "Garden view", "Work desk"],
    capacity: 2,
    status: "reserved",
    rating: 4.85,
  },
  {
    id: "room-3",
    name: "Regal Suite",
    type: "suite",
    description:
      "A generous suite with a separate lounge, king bed, and floor-to-ceiling windows looking over the city skyline.",
    price: 1450,
    images: roomImages(2),
    amenities: ["Free Wi-Fi", "Air conditioning", "Mini bar", "Lounge area", "Bathtub", "City view"],
    capacity: 3,
    status: "occupied",
    rating: 4.93,
  },
  {
    id: "room-4",
    name: "Executive Skyline",
    type: "executive",
    description:
      "Top-floor executive room built for business travel — a king bed, dedicated workspace, and lounge access.",
    price: 2100,
    images: roomImages(3),
    amenities: ["Free Wi-Fi", "Air conditioning", "Executive lounge access", "Work desk", "Mini bar", "Bathtub"],
    capacity: 2,
    status: "available",
    rating: 4.97,
  },
  {
    id: "room-5",
    name: "Courtyard Standard",
    type: "standard",
    description:
      "A cosy twin room facing the inner courtyard, freshly serviced and ready for a quick turnaround stay.",
    price: 460,
    images: roomImages(4),
    amenities: ["Free Wi-Fi", "Air conditioning", "Flat-screen TV"],
    capacity: 2,
    status: "needs_cleaning",
    rating: 4.61,
  },
  {
    id: "room-6",
    name: "Terrace Suite",
    type: "suite",
    description:
      "A suite with a private terrace and outdoor seating, undergoing scheduled maintenance this week.",
    price: 1600,
    images: roomImages(5),
    amenities: ["Free Wi-Fi", "Air conditioning", "Private terrace", "Mini bar", "Lounge area"],
    capacity: 3,
    status: "maintenance",
    rating: 4.88,
  },
  {
    id: "room-7",
    name: "Skyline Studio",
    type: "standard",
    description:
      "A well-lit studio with a queen bed and a fold-out desk, tucked on a quiet upper floor.",
    price: 510,
    images: roomImages(6),
    amenities: ["Free Wi-Fi", "Air conditioning", "Flat-screen TV", "Work desk"],
    capacity: 2,
    status: "available",
    rating: 4.68,
  },
  {
    id: "room-8",
    name: "Orchid Deluxe",
    type: "deluxe",
    description:
      "A deluxe room with warm wood tones, a king bed, and a reading nook by the window.",
    price: 810,
    images: roomImages(7),
    amenities: ["Free Wi-Fi", "Air conditioning", "Mini bar", "Work desk", "Reading nook"],
    capacity: 2,
    status: "reserved",
    rating: 4.79,
  },
  {
    id: "room-9",
    name: "Lakeview Suite",
    type: "suite",
    description:
      "A calm suite with a separate lounge and wide windows framing the lake, ideal for longer stays.",
    price: 1550,
    // A few extra Bedroom shots so this room demonstrates the multi-photo grid layout
    images: [
      ...roomImages(8),
      { url: roomPhotoPairs[0][0], category: "Bedroom" },
      { url: roomPhotoPairs[4][0], category: "Bedroom" },
      { url: roomPhotoPairs[10][0], category: "Bedroom" },
    ],
    amenities: ["Free Wi-Fi", "Air conditioning", "Mini bar", "Lounge area", "Lake view", "Bathtub"],
    capacity: 3,
    status: "available",
    rating: 4.91,
  },
  {
    id: "room-10",
    name: "Boardroom Executive",
    type: "executive",
    description:
      "An executive room built for extended business trips, with a private workspace and lounge access.",
    price: 2250,
    images: roomImages(9),
    amenities: ["Free Wi-Fi", "Air conditioning", "Executive lounge access", "Work desk", "Mini bar"],
    capacity: 2,
    status: "occupied",
    rating: 4.95,
  },
  {
    id: "room-11",
    name: "Palm Standard",
    type: "standard",
    description:
      "A simple, comfortable room with a queen bed and a view over the palm-lined courtyard.",
    price: 495,
    images: roomImages(10),
    amenities: ["Free Wi-Fi", "Air conditioning", "Flat-screen TV"],
    capacity: 2,
    status: "needs_cleaning",
    rating: 4.55,
  },
  {
    id: "room-12",
    name: "Ivory Deluxe",
    type: "deluxe",
    description:
      "A bright deluxe room finished in soft ivory tones, with a king bed and a walk-in wardrobe.",
    price: 760,
    images: roomImages(11),
    amenities: ["Free Wi-Fi", "Air conditioning", "Mini bar", "Walk-in wardrobe"],
    capacity: 2,
    status: "available",
    rating: 4.82,
  },
]

export const bookings: Booking[] = [
  {
    id: "booking-1",
    guestName: "Ama Boateng",
    guestEmail: "ama.boateng@example.com",
    guestPhone: "+233 24 111 2233",
    roomId: "room-1",
    roomName: "Harbour Standard",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(2),
    nights: 2,
    totalAmount: 960,
    depositPaid: 192,
    status: "confirmed",
    qrCode: "RML-8K2Q",
    bookedAt: isoDateOffset(-3),
    paymentMethod: "card",
  },
  {
    id: "booking-2",
    guestName: "Kwabena Owusu",
    guestEmail: "kwabena.owusu@example.com",
    guestPhone: "+233 20 222 3344",
    roomId: "room-4",
    roomName: "Executive Skyline",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(3),
    nights: 3,
    totalAmount: 6300,
    depositPaid: 1260,
    status: "confirmed",
    qrCode: "RML-4X9K",
    bookedAt: isoDateOffset(-5),
    paymentMethod: "mobile_money",
    vehiclePlate: "GT 4521-24",
  },
  {
    id: "booking-3",
    guestName: "Linda Mensah",
    guestEmail: "linda.mensah@example.com",
    guestPhone: "+233 26 333 4455",
    roomId: "room-3",
    roomName: "Regal Suite",
    checkIn: isoDateOffset(-1),
    checkOut: isoDateOffset(2),
    nights: 3,
    totalAmount: 4350,
    depositPaid: 4350,
    status: "checked_in",
    qrCode: "RML-2M7P",
    bookedAt: isoDateOffset(-6),
    paymentMethod: "cash",
    checkedInAt: isoDateTimeOffset(-1, 14, 32),
  },
  {
    id: "booking-4",
    guestName: "Samuel Tetteh",
    guestEmail: "samuel.tetteh@example.com",
    guestPhone: "+233 27 444 5566",
    roomId: "room-10",
    roomName: "Boardroom Executive",
    checkIn: isoDateOffset(-2),
    checkOut: isoDateOffset(1),
    nights: 3,
    totalAmount: 6750,
    depositPaid: 6750,
    status: "checked_in",
    qrCode: "RML-9V3L",
    bookedAt: isoDateOffset(-9),
    paymentMethod: "bank_transfer",
    vehiclePlate: "GR 1187-23",
    checkedInAt: isoDateTimeOffset(-2, 13, 10),
  },
  {
    id: "booking-5",
    guestName: "Grace Appiah",
    guestEmail: "grace.appiah@example.com",
    guestPhone: "+233 24 555 6677",
    roomId: "room-5",
    roomName: "Courtyard Standard",
    checkIn: isoDateOffset(-3),
    checkOut: isoDateOffset(-1),
    nights: 2,
    totalAmount: 920,
    depositPaid: 920,
    status: "checked_out",
    qrCode: "RML-6H1D",
    bookedAt: isoDateOffset(-12),
    paymentMethod: "card",
    checkedInAt: isoDateTimeOffset(-3, 15, 20),
    checkedOutAt: isoDateTimeOffset(-1, 11, 5),
  },
  {
    id: "booking-6",
    guestName: "Yaw Asante",
    guestEmail: "yaw.asante@example.com",
    guestPhone: "+233 20 666 7788",
    roomId: "room-11",
    roomName: "Palm Standard",
    checkIn: isoDateOffset(-5),
    checkOut: isoDateOffset(-3),
    nights: 2,
    totalAmount: 990,
    depositPaid: 990,
    status: "checked_out",
    qrCode: "RML-3T8N",
    bookedAt: isoDateOffset(-15),
    paymentMethod: "mobile_money",
    checkedInAt: isoDateTimeOffset(-5, 16, 0),
    checkedOutAt: isoDateTimeOffset(-3, 10, 45),
  },
  {
    id: "booking-7",
    guestName: "Comfort Nyarko",
    guestEmail: "comfort.nyarko@example.com",
    guestPhone: "+233 26 777 8899",
    roomId: "room-8",
    roomName: "Orchid Deluxe",
    checkIn: isoDateOffset(4),
    checkOut: isoDateOffset(6),
    nights: 2,
    totalAmount: 1620,
    depositPaid: 324,
    status: "confirmed",
    qrCode: "RML-5F6R",
    bookedAt: isoDateOffset(-1),
    paymentMethod: "cash",
  },
  {
    id: "booking-8",
    guestName: "Daniel Owusu",
    guestEmail: "daniel.owusu@example.com",
    guestPhone: "+233 27 888 9900",
    roomId: "room-2",
    roomName: "Garden Deluxe",
    checkIn: isoDateOffset(-1),
    checkOut: isoDateOffset(1),
    nights: 2,
    totalAmount: 1560,
    depositPaid: 312,
    status: "cancelled",
    qrCode: "RML-7QXA",
    bookedAt: isoDateOffset(-8),
    paymentMethod: "bank_transfer",
    refundStatus: "approved",
  },
  {
    id: "booking-9",
    guestName: "Efua Danso",
    guestEmail: "efua.danso@example.com",
    guestPhone: "+233 24 900 1122",
    roomId: "room-9",
    roomName: "Lakeview Suite",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(2),
    nights: 2,
    totalAmount: 3100,
    depositPaid: 620,
    status: "confirmed",
    qrCode: "RML-1A2B",
    bookedAt: isoDateOffset(-2),
    paymentMethod: "card",
  },
  {
    id: "booking-10",
    guestName: "Kwesi Boadu",
    guestEmail: "kwesi.boadu@example.com",
    guestPhone: "+233 27 900 3344",
    roomId: "room-12",
    roomName: "Ivory Deluxe",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(1),
    nights: 1,
    totalAmount: 760,
    depositPaid: 152,
    status: "confirmed",
    qrCode: "RML-3C4D",
    bookedAt: isoDateOffset(-1),
    paymentMethod: "mobile_money",
  },
  {
    id: "booking-11",
    guestName: "Abena Frimpong",
    guestEmail: "abena.frimpong@example.com",
    guestPhone: "+233 20 900 5566",
    roomId: "room-7",
    roomName: "Skyline Studio",
    checkIn: isoDateOffset(1),
    checkOut: isoDateOffset(3),
    nights: 2,
    totalAmount: 1020,
    depositPaid: 204,
    status: "confirmed",
    qrCode: "RML-5E6F",
    bookedAt: isoDateOffset(-1),
    paymentMethod: "cash",
  },
  {
    id: "booking-12",
    guestName: "Yaw Mensah",
    guestEmail: "yaw.mensah@example.com",
    guestPhone: "+233 26 900 7788",
    roomId: "room-9",
    roomName: "Lakeview Suite",
    checkIn: isoDateOffset(2),
    checkOut: isoDateOffset(4),
    nights: 2,
    totalAmount: 3100,
    depositPaid: 620,
    status: "confirmed",
    qrCode: "RML-7G8H",
    bookedAt: isoDateOffset(-1),
    paymentMethod: "bank_transfer",
  },
  {
    id: "booking-13",
    guestName: "Naa Adjei",
    guestEmail: "naa.adjei@example.com",
    guestPhone: "+233 27 900 9900",
    roomId: "room-12",
    roomName: "Ivory Deluxe",
    checkIn: isoDateOffset(5),
    checkOut: isoDateOffset(7),
    nights: 2,
    totalAmount: 1520,
    depositPaid: 304,
    status: "confirmed",
    qrCode: "RML-9I0J",
    bookedAt: isoDateOffset(-1),
    paymentMethod: "card",
  },
  {
    id: "booking-14",
    guestName: "Efua Boateng",
    guestEmail: "efua.boateng@example.com",
    guestPhone: "+233 24 111 2233",
    roomId: "room-6",
    roomName: "Terrace Suite",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(2),
    nights: 2,
    totalAmount: 3200,
    depositPaid: 640,
    status: "confirmed",
    qrCode: "RML-3K4L",
    bookedAt: isoDateOffset(-2),
    paymentMethod: "mobile_money",
  },
  {
    id: "booking-15",
    guestName: "Kwesi Owusu",
    guestEmail: "kwesi.owusu@example.com",
    guestPhone: "+233 20 222 3344",
    roomId: "room-1",
    roomName: "Harbour Standard",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(1),
    nights: 1,
    totalAmount: 480,
    depositPaid: 96,
    status: "confirmed",
    qrCode: "RML-5M6N",
    bookedAt: isoDateOffset(-3),
    paymentMethod: "cash",
  },
  {
    id: "booking-16",
    guestName: "Abena Frimpong",
    guestEmail: "abena.frimpong@example.com",
    guestPhone: "+233 26 444 5566",
    roomId: "room-11",
    roomName: "Palm Standard",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(3),
    nights: 3,
    totalAmount: 1485,
    depositPaid: 297,
    status: "confirmed",
    qrCode: "RML-7O8P",
    bookedAt: isoDateOffset(-4),
    paymentMethod: "bank_transfer",
  },
  {
    id: "booking-17",
    guestName: "Kofi Ansah",
    guestEmail: "kofi.ansah@example.com",
    guestPhone: "+233 27 555 6677",
    roomId: "room-8",
    roomName: "Orchid Deluxe",
    checkIn: isoDateOffset(0),
    checkOut: isoDateOffset(2),
    nights: 2,
    totalAmount: 1620,
    depositPaid: 324,
    status: "confirmed",
    qrCode: "RML-9Q0R",
    bookedAt: isoDateOffset(-2),
    paymentMethod: "card",
  },
]

export const auditLog: AuditLog[] = [
  {
    id: "audit-1",
    action: "Checked in guest — Regal Suite",
    performedBy: "Kojo A.",
    role: "receptionist",
    timestamp: "2026-09-04T08:12:00Z",
  },
  {
    id: "audit-2",
    action: "Checked out guest — Harbour Standard",
    performedBy: "Kojo A.",
    role: "receptionist",
    timestamp: "2026-09-04T10:47:00Z",
  },
  {
    id: "audit-3",
    action: "Approved refund for cancelled booking RML-7QXA",
    performedBy: "Efua B.",
    role: "manager",
    timestamp: "2026-09-04T11:20:00Z",
  },
  {
    id: "audit-4",
    action: "Marked Terrace Suite as under maintenance",
    performedBy: "Kojo A.",
    role: "receptionist",
    timestamp: "2026-09-03T09:05:00Z",
  },
  {
    id: "audit-5",
    action: "Cleared maintenance flag on Terrace Suite",
    performedBy: "Efua B.",
    role: "manager",
    timestamp: "2026-09-03T15:40:00Z",
  },
  {
    id: "audit-6",
    action: "Updated cancellation window to 48 hours",
    performedBy: "Nana Y.",
    role: "director",
    timestamp: "2026-09-02T13:00:00Z",
  },
  {
    id: "audit-7",
    action: "Flagged guest profile — repeated no-shows",
    performedBy: "Kojo A.",
    role: "receptionist",
    timestamp: "2026-09-02T17:30:00Z",
  },
  {
    id: "audit-8",
    action: "Processed walk-in booking — Skyline Studio",
    performedBy: "Ama S.",
    role: "receptionist",
    timestamp: "2026-09-01T12:15:00Z",
  },
  {
    id: "audit-9",
    action: "Reviewed monthly revenue report",
    performedBy: "Nana Y.",
    role: "director",
    timestamp: "2026-09-01T18:00:00Z",
  },
  {
    id: "audit-10",
    action: "Added new staff account — Front Desk",
    performedBy: "Efua B.",
    role: "manager",
    timestamp: "2026-08-31T09:45:00Z",
  },
]

export const staff: StaffMember[] = [
  {
    id: "staff-1",
    name: "Kojo A.",
    email: "kojo.receptionist@roomly.example",
    phone: "+233 24 555 0142",
    role: "receptionist",
    status: "on_shift",
    joinedAt: "2024-02-10",
  },
  {
    id: "staff-2",
    name: "Ama S.",
    email: "ama.receptionist@roomly.example",
    phone: "+233 20 555 0198",
    role: "receptionist",
    status: "off_shift",
    joinedAt: "2024-06-03",
  },
  {
    id: "staff-3",
    name: "Efua B.",
    email: "efua.manager@roomly.example",
    phone: "+233 26 555 0110",
    role: "manager",
    status: "on_shift",
    joinedAt: "2023-11-21",
  },
  {
    id: "staff-4",
    name: "Nana Y.",
    email: "nana.director@roomly.example",
    phone: "+233 27 555 0101",
    role: "director",
    status: "on_shift",
    joinedAt: "2022-05-14",
  },
]

export const maintenanceIssues: MaintenanceIssue[] = [
  {
    id: "maintenance-1",
    roomId: "room-6",
    roomName: "Terrace Suite",
    description: "Terrace door lock is sticking and needs a replacement latch.",
    reportedBy: "Kojo A.",
    reportedAt: isoDateOffset(-2),
    status: "open",
  },
  {
    id: "maintenance-2",
    roomId: "room-1",
    roomName: "Harbour Standard",
    description: "Air conditioning was cycling loudly — technician replaced a worn fan belt.",
    reportedBy: "Ama S.",
    reportedAt: isoDateOffset(-9),
    status: "resolved",
    resolvedAt: isoDateOffset(-7),
  },
]

export const promoCodes: PromoCode[] = [
  { id: "promo-1", code: "WELCOME10", discountPercent: 10, active: true, createdAt: isoDateOffset(-40) },
  { id: "promo-2", code: "LONGSTAY15", discountPercent: 15, active: true, createdAt: isoDateOffset(-25) },
  { id: "promo-3", code: "OFFSEASON20", discountPercent: 20, active: false, createdAt: isoDateOffset(-60) },
]

export const reviews: Review[] = [
  {
    id: "review-1",
    roomId: "room-1",
    guestName: "Kwame A.",
    rating: 5,
    comment: "Small but perfectly kept — great value for a short stay near the harbour.",
    date: "2026-07-12",
  },
  {
    id: "review-2",
    roomId: "room-1",
    guestName: "Linda O.",
    rating: 4,
    comment: "Comfortable bed and quiet at night. Would book again.",
    date: "2026-06-02",
  },
  {
    id: "review-3",
    roomId: "room-2",
    guestName: "Yaw B.",
    rating: 5,
    comment: "The garden view was a lovely surprise, and the sitting area made it easy to work remotely.",
    date: "2026-07-01",
  },
  {
    id: "review-4",
    roomId: "room-2",
    guestName: "Efua M.",
    rating: 5,
    comment: "Spacious and well finished. The mini bar was a nice touch.",
    date: "2026-05-20",
  },
  {
    id: "review-5",
    roomId: "room-3",
    guestName: "Daniel K.",
    rating: 5,
    comment: "The lounge area made it feel like a real suite, not just a bigger room. Stunning skyline view.",
    date: "2026-07-18",
  },
  {
    id: "review-6",
    roomId: "room-3",
    guestName: "Grace T.",
    rating: 5,
    comment: "Booked this for an anniversary stay and it did not disappoint.",
    date: "2026-04-09",
  },
  {
    id: "review-7",
    roomId: "room-4",
    guestName: "Michael S.",
    rating: 5,
    comment: "Exactly what I needed for a work trip — fast Wi-Fi, a real desk, and a quiet floor.",
    date: "2026-08-01",
  },
  {
    id: "review-8",
    roomId: "room-4",
    guestName: "Abena D.",
    rating: 5,
    comment: "Lounge access was worth it on its own. Will be back for my next business trip.",
    date: "2026-06-14",
  },
  {
    id: "review-9",
    roomId: "room-5",
    guestName: "Priscilla N.",
    rating: 4,
    comment: "Simple, clean, and the courtyard is quieter than it looks from the photos.",
    date: "2026-05-03",
  },
  {
    id: "review-10",
    roomId: "room-6",
    guestName: "Kofi R.",
    rating: 5,
    comment: "The private terrace made mornings there unforgettable.",
    date: "2026-03-22",
  },
  {
    id: "review-11",
    roomId: "room-7",
    guestName: "Nana Y.",
    rating: 5,
    comment: "Bright room, and the fold-out desk was surprisingly useful.",
    date: "2026-07-27",
  },
  {
    id: "review-12",
    roomId: "room-8",
    guestName: "Esi P.",
    rating: 5,
    comment: "That reading nook by the window sold me. Warm, cosy, and quiet.",
    date: "2026-06-30",
  },
  {
    id: "review-13",
    roomId: "room-9",
    guestName: "Samuel L.",
    rating: 5,
    comment: "Woke up to the lake view every morning — worth every cedi.",
    date: "2026-08-05",
  },
  {
    id: "review-14",
    roomId: "room-10",
    guestName: "Comfort A.",
    rating: 5,
    comment: "Ran a full day of calls from the room and never had a single issue.",
    date: "2026-07-09",
  },
  {
    id: "review-15",
    roomId: "room-11",
    guestName: "Ibrahim F.",
    rating: 4,
    comment: "No frills, just a comfortable room at a fair price.",
    date: "2026-04-28",
  },
  {
    id: "review-16",
    roomId: "room-12",
    guestName: "Adjoa W.",
    rating: 5,
    comment: "The walk-in wardrobe was unexpected for this price point. Loved it.",
    date: "2026-06-17",
  },
  {
    id: "review-17",
    roomId: "room-1",
    guestName: "Ato B.",
    rating: 5,
    comment: "Check-in was fast and the room was spotless when I arrived.",
    date: "2026-03-14",
  },
  {
    id: "review-18",
    roomId: "room-2",
    guestName: "Sandra Q.",
    rating: 4,
    comment: "Loved the natural light in the mornings. A bit noisy on weekends.",
    date: "2026-04-22",
  },
  {
    id: "review-19",
    roomId: "room-3",
    guestName: "Emmanuel O.",
    rating: 5,
    comment: "Worth every cedi. The bathtub alone made it feel like a real getaway.",
    date: "2026-02-27",
  },
  {
    id: "review-20",
    roomId: "room-4",
    guestName: "Rita N.",
    rating: 5,
    comment: "Best executive room I've stayed in locally — quiet, fast Wi-Fi, great desk chair.",
    date: "2026-05-11",
  },
  {
    id: "review-21",
    roomId: "room-5",
    guestName: "Joseph T.",
    rating: 5,
    comment: "Small room, but everything worked and it was very well priced.",
    date: "2026-07-03",
  },
  {
    id: "review-22",
    roomId: "room-6",
    guestName: "Naa A.",
    rating: 4,
    comment: "The terrace view is real. Book it if the weather's good.",
    date: "2026-01-19",
  },
  {
    id: "review-23",
    roomId: "room-7",
    guestName: "Patrick M.",
    rating: 4,
    comment: "Compact but smartly laid out. Good for a one-night stopover.",
    date: "2026-04-05",
  },
  {
    id: "review-24",
    roomId: "room-8",
    guestName: "Vivian K.",
    rating: 5,
    comment: "The wood tones made it feel warm rather than generic. Really enjoyed it.",
    date: "2026-03-30",
  },
  {
    id: "review-25",
    roomId: "room-9",
    guestName: "Bright A.",
    rating: 5,
    comment: "Perfect for our anniversary weekend. Would book the same room again.",
    date: "2026-02-14",
  },
  {
    id: "review-26",
    roomId: "room-10",
    guestName: "Diana F.",
    rating: 5,
    comment: "Lounge access plus a quiet room made this ideal for back-to-back meetings.",
    date: "2026-05-27",
  },
  {
    id: "review-27",
    roomId: "room-11",
    guestName: "Solomon G.",
    rating: 4,
    comment: "Did the job for a short stopover. Nothing fancy, nothing wrong either.",
    date: "2026-06-08",
  },
  {
    id: "review-28",
    roomId: "room-12",
    guestName: "Mavis R.",
    rating: 5,
    comment: "Ivory tones and good lighting made every photo I took look great.",
    date: "2026-07-21",
  },
]
